Added BlogPage
girlscript/feminist-bible-phase-2 pull request #120
Opened 2020-10-14 07:47 UTC by Shubham-1105

fixes #50 

I am getting issue in removing the padding between the grid containers

![Screenshot (458)](https://user-images.githubusercontent.com/42351806/95959001-8c90b180-0e1f-11eb-8ce9-19f4725b3778.png)
![Screenshot (459)](https://user-images.githubusercontent.com/42351806/95959014-8ef30b80-0e1f-11eb-91ef-ac1b16e51e8e.png)

**Addition Information (if any)** <br/>
Mention any additional information that has been taken note of while making the PR, or needs to be taken note of while reviewing the PR. Ignore if none.

2020-10-14 09:15 UTC, salil-naik requested changes
There is no need to use grid-y.  Every block element by default comes one below another. 

- [ ] Do not use grid-y anywhere
- [ ] Rewrite the code as you have taken `grid-container` and `grid-y` everywhere. `grid-container` is required only twice for this page. One for the top part, and one for the article. Remove all others.
- [ ] Run scss and jsx through [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode). 
- [ ] Use avatar component
- [ ] Follow the grid columns properly

2020-10-14 09:15 UTC, salil-naik commented on frontend/src/pages/BlogPage.jsx
> +            <div style={{ background: "#FFFDF6" }}>
style is not required as you have already given it in css

2020-10-14 09:15 UTC, salil-naik commented on frontend/src/pages/BlogPage.jsx
> +                  <img src={BlogImage}  className="hero_blogImage"alt="Blog"/>
This is not as per design.

2020-10-14 09:15 UTC, salil-naik commented on frontend/src/pages/BlogPage.jsx
> +                    <div className="grid-container">
x-y grid should not be used here. Use flex instead.

2020-10-14 09:15 UTC, salil-naik commented on frontend/src/pages/BlogPage.jsx
> +                      <div className="grid-x">
x-y grid should not be used here. Use flex

2020-10-14 09:15 UTC, salil-naik commented on frontend/src/pages/BlogPage.jsx
> +              <div className="grid-conatiner fluid">
Remove the `fluid` class

2020-10-14 09:15 UTC, salil-naik commented on frontend/src/pages/BlogPage.jsx
> +                  <div className="cell large-8">
Use `large offset` to keep the article section in the center.

2020-10-14 09:15 UTC, salil-naik commented on frontend/src/pages/BlogPage.jsx
> +                  <div className="grid-container">
`grid-container` class should only be used once. You have used it almost everywhere.

2020-10-14 09:15 UTC, salil-naik commented on frontend/src/css/pages/BlogPage.scss
> +        border: 10px solid black;
border is not required

2020-10-14 09:15 UTC, salil-naik commented on frontend/src/css/pages/BlogPage.scss
> +      font-weight: bolder;
There are scss classes made for font-weight and colours

2020-10-14 20:05 UTC, Shubham-1105 commented
@salil-naik corrected the structure but getting issue in removing padding
![Screenshot (462)](https://user-images.githubusercontent.com/42351806/96039633-9b5e7f00-0e86-11eb-84db-14104c9e2ca9.png)
![Screenshot (463)](https://user-images.githubusercontent.com/42351806/96039639-9e596f80-0e86-11eb-9df2-d78bedf6affe.png)

2020-10-15 13:20 UTC, salil-naik approved these changes

2020-10-15 13:20 UTC, merged