Responsive coc page
girlscript/feminist-bible-phase-2 pull request #145
Opened 2020-11-04 07:43 UTC by shwetalsoni

### Fixes #132

2020-11-05 08:59 UTC, salil-naik requested changes
Hi. Please check your code. 6 backend files are edited in your PR.

2020-11-05 09:03 UTC, shwetalsoni commented
@salil-naik  sir I didn't editted any of them but when i pulled the changes they were shown in my git tree . So i had to commit them to avoid any conflicts

2020-11-05 09:31 UTC, salil-naik requested changes

2020-11-05 09:31 UTC, salil-naik commented on frontend/src/App.js
> +import Notification from"./components/Notification.jsx";
why have you called this here?

2020-11-05 09:31 UTC, salil-naik commented on frontend/src/App.js
> +import AboutUs from "./pages/AboutUs";
add .jsx

2020-11-05 09:31 UTC, salil-naik commented on frontend/src/App.js
> +import AdminProfile from "./pages/adminProfile";
add .jsx

2020-11-05 09:31 UTC, salil-naik commented on frontend/src/css/settings/_global.scss
> -@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap');
Revert this file to as it was before.

2020-11-05 14:22 UTC, salil-naik commented
@shwetalsoni please attach mobile and tablet screenshots. 
@gauravdas014 please have a look at the backend files and let me know if it's okay to approve the PR.

2020-11-05 14:38 UTC, gauravdas014 requested changes
Might have forgotten to do a git pull. Merging the PR will break the backend code. Some files have been removed, and some have been edited in this pr. Details are as follows:
1. in app.js line 12 and 44 is removed, which should not be removed
2. swaggerDefinition.js file have been removed earlier, so this file should not be again marge them to master.
3. projectController.js should not be removed as it's being used in project section. Current PR is deleting the file
4. forumPostCommentModel should not be removed
5.authRoutes.js is updated, it was edited later on
6. Some lines are deleted in projectRoutes.js, that must not happen

2020-11-05 14:40 UTC, gauravdas014 commented
@salil-naik the pr needs a lot of changes. The local repo of @shwetalsoni was not updated

2020-11-05 14:47 UTC, shwetalsoni commented
@gauravdas014 when i pulled the changes from upstream the files you mentioned being deleted or changed were already that way before. I didn't know why it was shown in git tree on being pulled. So i had to commit them. 

If you know how to fix this lemme know please.

2020-11-05 14:55 UTC, gauravdas014 commented
@shwetalsoni can you revert the commit which added all those unnecessary changes?

2020-11-05 15:00 UTC, shwetalsoni commented
@gauravdas014  I ll do it  as soon i get free

2020-11-05 17:29 UTC, shwetalsoni commented
@gauravdas014 I have reverted the files . Please check if everything is fine

2020-11-06 05:56 UTC, gauravdas014 commented
@shwetalsoni Just remove the swaggerDefinition.js file, rest looks fine to me.

2020-11-06 06:44 UTC, shwetalsoni commented
@gauravdas014 Done
@salil-naik Please check if anymore changes are to be done

2020-11-06 06:46 UTC, gauravdas014 approved these changes

2020-11-06 06:47 UTC, gauravdas014 commented
@shwetalsoni looks good to me. Thanks!

2020-11-08 16:20 UTC, salil-naik commented
Thanks a lot for your help @gauravdas014

2020-11-08 19:27 UTC, merged