Created Footer
girlscript/feminist-bible-phase-2 pull request #59
Opened 2020-09-14 21:13 UTC by joharikushagra

Fix #17 
created footer component

2020-09-16 04:51 UTC, salil-naik requested changes
Foundation grid is used perfectly. 

- [ ] Add footer screenshot
- [ ] Remove `ul` from `p`. `p` is not required there. 
- [ ] SCSS filename should be footer.scss. Remove underscore. 
- [ ] Give the following classes

> `footer__sub-title` (remove text__head)
> `footer__nav-item-container` (for ul)
> `footer__nav-item` (for li)
> replace vote__of__thanks with `footer__credits`

2020-09-16 06:42 UTC, joharikushagra commented
okay I'll make the changes

2020-09-16 07:29 UTC, joharikushagra commented
![footer1](https://user-images.githubusercontent.com/57484457/93305670-768dd200-f81c-11ea-9b71-cce1d1a26cf4.JPG)

2020-09-17 02:17 UTC, salil-naik commented on frontend/src/css/components/footer.scss
> +    .grid-container{
never overwrite frameworks classes like grid-x, grid-container, cell, etc.

2020-09-17 02:17 UTC, salil-naik commented on frontend/src/css/components/footer.scss
> +    .cell{
framework class

2020-09-17 02:17 UTC, salil-naik commented on frontend/src/css/components/footer.scss
> +.large-2{
framework class

2020-09-17 02:17 UTC, salil-naik commented on frontend/src/css/components/footer.scss
> +.footer__nav-item{
You could have used scss nesting.

2020-09-17 02:18 UTC, merged

2020-09-17 03:54 UTC, joharikushagra commented on frontend/src/css/components/footer.scss
> +.footer__nav-item{
Okay I'll remember that:)